<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { replaceSessionStaff } from '@/services/commands'
import { getMySessions, getSessionStaff, getStaff } from '@/services/data-queries'
import { formatDateTime } from '@/shared/utils/format'

const sessions = ref<any[]>([]); const staff = ref<any[]>([]); const assignments = ref<any[]>([]); const selected = ref<any | null>(null); const form = ref({ original_staff_id: '', replacement_staff_id: '', reason: '' }); const errorMessage = ref(''); const successMessage = ref(''); const loading = ref(false)
async function load() { loading.value = true; try { [sessions.value, staff.value] = await Promise.all([getMySessions(), getStaff()]) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tải session' } finally { loading.value = false } }
async function selectSession(row: any) { selected.value = row; assignments.value = await getSessionStaff(row.id) as any[]; form.value.original_staff_id = assignments.value[0]?.staff_id || ''; form.value.replacement_staff_id = ''; form.value.reason = '' }
async function replace() { if (!selected.value) return; try { await replaceSessionStaff(selected.value.id, form.value.original_staff_id, form.value.replacement_staff_id, form.value.reason); successMessage.value = 'Đã ghi nhận dạy thay và audit.'; await selectSession(selected.value) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể thay nhân sự' } }
onMounted(load)
</script>

<template>
  <div class="d-flex justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Academic</div><h1 class="h3 mb-0">Tất cả buổi học</h1></div><button class="btn btn-outline-primary" @click="load">Làm mới</button></div>
  <div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div><div v-if="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
  <div class="row g-4"><div class="col-12 col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><button v-for="row in sessions" :key="row.id" class="btn w-100 text-start border-bottom rounded-0 py-3" :class="selected?.id === row.id ? 'bg-primary-subtle' : ''" @click="selectSession(row)"><div class="d-flex justify-content-between"><span class="fw-semibold">{{ row.class_months?.classes?.name || 'Lớp học' }}</span><span class="badge text-bg-light">{{ row.status }}</span></div><small class="text-secondary">{{ formatDateTime(row.scheduled_start_at) }}</small></button><div v-if="!loading && !sessions.length" class="text-center text-secondary py-5">Chưa có session</div></div></div></div><div class="col-12 col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">Phân công và dạy thay</h2><div v-if="selected"><div class="small text-secondary mb-3">{{ formatDateTime(selected.scheduled_start_at) }}</div><div v-for="item in assignments" :key="item.id" class="small border-bottom py-2">{{ item.staff?.full_name }} — {{ item.assignment_role }}<span v-if="item.is_replacement" class="badge text-bg-info ms-2">Dạy thay</span></div><div class="row g-2 mt-3"><div class="col-12"><label class="form-label">Nhân sự gốc</label><select v-model="form.original_staff_id" class="form-select"><option v-for="item in assignments" :key="item.staff_id" :value="item.staff_id">{{ item.staff?.full_name }}</option></select></div><div class="col-12"><label class="form-label">Nhân sự thay</label><select v-model="form.replacement_staff_id" class="form-select"><option value="">Chọn nhân sự</option><option v-for="item in staff.filter((candidate) => !assignments.some((assigned) => assigned.staff_id === candidate.id))" :key="item.id" :value="item.id">{{ item.full_name }}</option></select></div><div class="col-12"><label class="form-label">Lý do</label><textarea v-model="form.reason" class="form-control" rows="2"></textarea></div><div class="col-12"><button class="btn btn-primary" :disabled="selected.status === 'COMPLETED' || !form.original_staff_id || !form.replacement_staff_id || !form.reason" @click="replace">Lưu dạy thay</button></div></div></div><div v-else class="text-center text-secondary py-5">Chọn một session để xem phân công.</div></div></div></div></div>
</template>
