<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { createClass } from '@/services/commands'
import { getClasses, getGrades, getSubjects } from '@/services/data-queries'
import { formatVnd } from '@/shared/utils/format'

const rows = ref<any[]>([]); const subjects = ref<any[]>([]); const grades = ref<any[]>([]); const showForm = ref(false); const errorMessage = ref(''); const successMessage = ref(''); const loading = ref(false)
const form = ref({ code: '', name: '', subject_id: '', grade_id: '', default_monthly_fee: 0, max_students: null as number | null, capacity_policy: 'UNLIMITED' as 'WARNING' | 'BLOCK' | 'UNLIMITED' })
async function load() { loading.value = true; try { [rows.value, subjects.value, grades.value] = await Promise.all([getClasses(), getSubjects(), getGrades()]) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tải lớp học' } finally { loading.value = false } }
async function create() { errorMessage.value = ''; try { await createClass({ ...form.value, max_students: form.value.capacity_policy === 'UNLIMITED' ? null : form.value.max_students }); successMessage.value = 'Đã tạo lớp học.'; showForm.value = false; form.value = { code: '', name: '', subject_id: '', grade_id: '', default_monthly_fee: 0, max_students: null, capacity_policy: 'UNLIMITED' }; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tạo lớp học' } }
onMounted(load)
</script>

<template>
  <div class="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Core</div><h1 class="h3 mb-0">Lớp học</h1></div><button class="btn btn-primary" @click="showForm = !showForm">{{ showForm ? 'Đóng form' : 'Thêm lớp' }}</button></div>
  <div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div><div v-if="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
  <div v-if="showForm" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">Mã lớp</label><input v-model="form.code" class="form-control" /></div><div class="col-md-5"><label class="form-label">Tên lớp</label><input v-model="form.name" class="form-control" /></div><div class="col-md-2"><label class="form-label">Môn</label><select v-model="form.subject_id" class="form-select"><option value="">Chọn</option><option v-for="item in subjects" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><div class="col-md-2"><label class="form-label">Khối</label><select v-model="form.grade_id" class="form-select"><option value="">Chọn</option><option v-for="item in grades" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><div class="col-md-4"><label class="form-label">Học phí mặc định (VND)</label><input v-model.number="form.default_monthly_fee" type="number" min="0" class="form-control" /></div><div class="col-md-4"><label class="form-label">Chính sách sĩ số</label><select v-model="form.capacity_policy" class="form-select"><option value="UNLIMITED">Không giới hạn</option><option value="WARNING">Cảnh báo</option><option value="BLOCK">Chặn</option></select></div><div v-if="form.capacity_policy !== 'UNLIMITED'" class="col-md-4"><label class="form-label">Sĩ số tối đa</label><input v-model.number="form.max_students" type="number" min="1" class="form-control" /></div></div><button class="btn btn-success mt-3" :disabled="!form.code || !form.name || !form.subject_id || !form.grade_id" @click="create">Lưu lớp</button></div></div>
  <div class="card border-0 shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Mã</th><th>Tên lớp</th><th>Môn</th><th>Khối</th><th>Học phí</th><th>Sĩ số</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><code>{{ row.code }}</code></td><td class="fw-semibold">{{ row.name }}</td><td>{{ row.subjects?.name || '—' }}</td><td>{{ row.grades?.name || '—' }}</td><td>{{ formatVnd(row.default_monthly_fee) }}</td><td>{{ row.capacity_policy === 'UNLIMITED' ? 'Không giới hạn' : row.max_students }}</td></tr><tr v-if="!loading && !rows.length"><td colspan="6" class="text-center text-secondary py-4">Chưa có dữ liệu</td></tr></tbody></table></div></div></div>
</template>
