<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { activateClassMonth, addClassMonthSchedule, addClassMonthStaff, addClassMonthStudent, createClassMonth } from '@/services/commands'
import { getClassMonths, getClasses, getStaff, getStudents } from '@/services/data-queries'

const months = ref<any[]>([]); const classes = ref<any[]>([]); const students = ref<any[]>([]); const staff = ref<any[]>([]); const showForm = ref(false); const errorMessage = ref(''); const successMessage = ref(''); const selectedMonth = ref<any | null>(null)
const overrideConflicts = ref(false)
const monthForm = ref({ class_id: '', year: new Date().getFullYear(), month: new Date().getMonth() + 1, notes: '' }); const studentForm = ref({ student_id: '', membership_start_date: '', monthly_fee_snapshot: 0 }); const staffForm = ref({ staff_id: '', assignment_role: 'TEACHER' as 'TEACHER' | 'ASSISTANT' }); const scheduleForm = ref({ day_of_week: 1, start_time: '17:30', end_time: '19:00' })
const selectedClass = computed(() => classes.value.find((item) => item.id === monthForm.value.class_id))
async function load() { try { [months.value, classes.value, students.value, staff.value] = await Promise.all([getClassMonths(), getClasses(), getStudents(), getStaff()]) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tải tháng vận hành' } }
async function createMonth() { try { selectedMonth.value = await createClassMonth(monthForm.value); successMessage.value = 'Đã tạo ClassMonth DRAFT. Hãy thêm học sinh, nhân sự và lịch.'; showForm.value = true; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tạo ClassMonth' } }
function selectMonth(month: any) { selectedMonth.value = month; showForm.value = true; monthForm.value.class_id = month.class_id }
async function addStudent() { if (!selectedMonth.value) return; try { await addClassMonthStudent({ class_month_id: selectedMonth.value.id, student_id: studentForm.value.student_id, membership_start_date: studentForm.value.membership_start_date || `${monthForm.value.year}-${String(monthForm.value.month).padStart(2, '0')}-01`, monthly_fee_snapshot: studentForm.value.monthly_fee_snapshot || selectedClass.value?.default_monthly_fee || 0 }); successMessage.value = 'Đã thêm học sinh vào snapshot tháng.' } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể thêm học sinh' } }
async function addStaff() { if (!selectedMonth.value) return; try { await addClassMonthStaff({ class_month_id: selectedMonth.value.id, ...staffForm.value }); successMessage.value = 'Đã thêm nhân sự vào snapshot tháng.' } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể thêm nhân sự' } }
async function addSchedule() { if (!selectedMonth.value) return; try { await addClassMonthSchedule({ class_month_id: selectedMonth.value.id, ...scheduleForm.value }); successMessage.value = 'Đã thêm lịch học.' } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể thêm lịch học' } }
async function activate() { if (!selectedMonth.value) return; try { await activateClassMonth(selectedMonth.value.id, overrideConflicts.value); successMessage.value = 'ClassMonth đã ACTIVE và session/tuition đã được sinh.'; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể activate ClassMonth' } }
onMounted(load)
</script>

<template>
  <div class="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Academic</div><h1 class="h3 mb-0">Tháng vận hành</h1></div><button class="btn btn-primary" @click="showForm = !showForm">{{ showForm ? 'Đóng' : 'Tạo ClassMonth DRAFT' }}</button></div>
  <div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div><div v-if="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
  <div v-if="showForm" class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h6">{{ selectedMonth ? `Cấu hình ${selectedMonth.year}/${selectedMonth.month}` : 'Tạo tháng mới' }}</h2><div v-if="!selectedMonth" class="row g-3"><div class="col-md-6"><label class="form-label">Lớp</label><select v-model="monthForm.class_id" class="form-select"><option value="">Chọn lớp</option><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.code }} — {{ item.name }}</option></select></div><div class="col-md-3"><label class="form-label">Năm</label><input v-model.number="monthForm.year" type="number" class="form-control" /></div><div class="col-md-3"><label class="form-label">Tháng</label><input v-model.number="monthForm.month" type="number" min="1" max="12" class="form-control" /></div><button class="btn btn-success mt-3" :disabled="!monthForm.class_id" @click="createMonth">Tạo DRAFT</button></div><div v-else class="row g-3"><div class="col-md-4"><label class="form-label">Thêm học sinh</label><select v-model="studentForm.student_id" class="form-select"><option value="">Chọn học sinh</option><option v-for="item in students" :key="item.id" :value="item.id">{{ item.student_code }} — {{ item.full_name }}</option></select><button class="btn btn-outline-primary btn-sm mt-2" @click="addStudent">Thêm học sinh</button></div><div class="col-md-4"><label class="form-label">Thêm nhân sự</label><select v-model="staffForm.staff_id" class="form-select"><option value="">Chọn nhân sự</option><option v-for="item in staff" :key="item.id" :value="item.id">{{ item.full_name }}</option></select><select v-model="staffForm.assignment_role" class="form-select mt-2"><option value="TEACHER">Giáo viên</option><option value="ASSISTANT">Trợ giảng</option></select><button class="btn btn-outline-primary btn-sm mt-2" @click="addStaff">Thêm nhân sự</button></div><div class="col-md-4"><label class="form-label">Thêm lịch</label><select v-model.number="scheduleForm.day_of_week" class="form-select"><option v-for="day in 7" :key="day" :value="day">Thứ {{ day === 7 ? 'CN' : day + 1 }}</option></select><div class="input-group mt-2"><input v-model="scheduleForm.start_time" type="time" class="form-control" /><input v-model="scheduleForm.end_time" type="time" class="form-control" /></div><button class="btn btn-outline-primary btn-sm mt-2" @click="addSchedule">Thêm lịch</button></div><div class="col-12"><label class="form-check"><input v-model="overrideConflicts" class="form-check-input" type="checkbox" /><span class="form-check-label small">Cho phép override trùng lịch (bắt buộc audit)</span></label><button class="btn btn-success mt-2" :disabled="selectedMonth.status !== 'DRAFT'" @click="activate">Xác nhận ACTIVE và sinh session</button></div></div></div></div>
  <div class="card border-0 shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Lớp</th><th>Tháng</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-for="row in months" :key="row.id"><td>{{ row.classes?.code }} — {{ row.classes?.name }}</td><td>{{ row.month }}/{{ row.year }}</td><td><span class="badge" :class="row.status === 'ACTIVE' ? 'text-bg-success' : 'text-bg-warning'">{{ row.status }}</span></td><td><button v-if="row.status === 'DRAFT'" class="btn btn-sm btn-outline-primary" @click="selectMonth(row)">Cấu hình</button></td></tr><tr v-if="!months.length"><td colspan="4" class="text-center text-secondary py-4">Chưa có ClassMonth</td></tr></tbody></table></div></div></div>
</template>
