<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { confirmTuitionPaid, createManualAccounting } from '@/services/commands'
import { getAccountingCategories, getAccountingTransactions, getTuitionRecords } from '@/services/data-queries'
import { formatDateTime, formatVnd } from '@/shared/utils/format'

const rows = ref<any[]>([])
const transactions = ref<any[]>([])
const categories = ref<any[]>([])
const loading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')
const paymentMethod = ref<'CASH' | 'BANK_TRANSFER' | 'OTHER'>('CASH')
const showForm = ref(false)
const form = ref({ direction: 'EXPENSE' as 'INCOME' | 'EXPENSE', category_id: '', amount: 0, transaction_date: new Date().toISOString().slice(0, 10), payment_method: 'CASH' as 'CASH' | 'BANK_TRANSFER' | 'OTHER', description: '' })
const income = computed(() => transactions.value.filter((row) => row.direction === 'INCOME').reduce((sum, row) => sum + Number(row.amount || 0), 0))
const expense = computed(() => transactions.value.filter((row) => row.direction === 'EXPENSE').reduce((sum, row) => sum + Number(row.amount || 0), 0))
const formCategories = computed(() => categories.value.filter((row) => row.direction === form.value.direction))

async function load() { loading.value = true; errorMessage.value = ''; try { [rows.value, transactions.value, categories.value] = await Promise.all([getTuitionRecords(), getAccountingTransactions(), getAccountingCategories()]) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tải dữ liệu tài chính' } finally { loading.value = false } }
async function markPaid(row: any) { try { await confirmTuitionPaid(row.id, paymentMethod.value); successMessage.value = `Đã xác nhận học phí ${row.students?.full_name || ''}.`; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể xác nhận học phí' } }
async function saveManual() { try { await createManualAccounting({ ...form.value, amount: Math.trunc(form.value.amount), category_id: form.value.category_id }); successMessage.value = 'Đã tạo giao dịch MANUAL và audit.'; showForm.value = false; form.value = { direction: 'EXPENSE', category_id: '', amount: 0, transaction_date: new Date().toISOString().slice(0, 10), payment_method: 'CASH', description: '' }; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tạo giao dịch' } }
onMounted(load)
</script>

<template>
  <div class="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Finance</div><h1 class="h3 mb-0">Tài chính</h1></div><div class="d-flex gap-2"><select v-model="paymentMethod" class="form-select"><option value="CASH">Tiền mặt</option><option value="BANK_TRANSFER">Chuyển khoản</option><option value="OTHER">Khác</option></select><button class="btn btn-outline-primary" @click="load">Làm mới</button><button class="btn btn-primary" @click="showForm = !showForm">{{ showForm ? 'Đóng form' : 'Thêm thu/chi' }}</button></div></div>
  <div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div><div v-if="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
  <div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">Tổng thu thực tế</div><div class="h5 text-success mb-0">{{ formatVnd(income) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">Tổng chi thực tế</div><div class="h5 text-danger mb-0">{{ formatVnd(expense) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">Lợi nhuận</div><div class="h5 mb-0">{{ formatVnd(income - expense) }}</div></div></div></div></div>
  <div v-if="showForm" class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h6">Giao dịch MANUAL</h2><div class="row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Loại</label><select v-model="form.direction" class="form-select"><option value="INCOME">Thu</option><option value="EXPENSE">Chi</option></select></div><div class="col-md-3"><label class="form-label">Danh mục</label><select v-model="form.category_id" class="form-select"><option value="">Chọn danh mục</option><option v-for="item in formCategories" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><div class="col-md-2"><label class="form-label">Số tiền</label><input v-model.number="form.amount" type="number" min="1" class="form-control" /></div><div class="col-md-2"><label class="form-label">Ngày</label><input v-model="form.transaction_date" type="date" class="form-control" /></div><div class="col-md-3"><label class="form-label">Mô tả</label><input v-model="form.description" class="form-control" /></div><div class="col-12"><button class="btn btn-success" :disabled="!form.category_id || !form.amount || !form.description" @click="saveManual">Lưu giao dịch</button></div></div></div></div>
  <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h6">Học phí</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Học sinh</th><th>Tháng</th><th>Phải thu</th><th>Đã thu</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><div class="fw-semibold">{{ row.students?.full_name }}</div><small class="text-secondary">{{ row.students?.student_code }}</small></td><td>{{ row.class_months?.month }}/{{ row.class_months?.year }}</td><td>{{ formatVnd(row.amount_due) }}</td><td>{{ formatVnd(row.amount_paid) }}</td><td><span class="badge" :class="row.status === 'PAID' ? 'text-bg-success' : 'text-bg-warning'">{{ row.status }}</span></td><td><button v-if="row.status === 'UNPAID'" class="btn btn-sm btn-success" @click="markPaid(row)">Xác nhận đã thu</button><small v-else>{{ formatDateTime(row.paid_at) }}</small></td></tr><tr v-if="!loading && !rows.length"><td colspan="6" class="text-center text-secondary py-4">Chưa có học phí</td></tr></tbody></table></div></div></div>
  <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">Sổ thu/chi</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Ngày</th><th>Loại</th><th>Danh mục</th><th>Nguồn</th><th>Số tiền</th><th>Mô tả</th></tr></thead><tbody><tr v-for="row in transactions" :key="row.id"><td>{{ row.transaction_date }}</td><td><span :class="row.direction === 'INCOME' ? 'text-success' : 'text-danger'">{{ row.direction }}</span></td><td>{{ row.accounting_categories?.name || '—' }}</td><td><span class="badge text-bg-light">{{ row.transaction_type }}</span></td><td>{{ formatVnd(row.amount) }}</td><td>{{ row.description || '—' }}</td></tr><tr v-if="!loading && !transactions.length"><td colspan="6" class="text-center text-secondary py-4">Chưa có giao dịch</td></tr></tbody></table></div></div></div>
</template>
