<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminCreateUser, adminResetPassword, setAccountStatus } from '@/services/commands'
import { getStaff } from '@/services/data-queries'

interface Staff { id: string; user_id: string; staff_code: string | null; full_name: string; staff_type: string; phone: string | null; status: string }
const rows = ref<Staff[]>([]); const search = ref(''); const showForm = ref(false); const loading = ref(false); const errorMessage = ref(''); const successMessage = ref(''); const temporaryPassword = ref('')
const form = ref({ full_name: '', staff_code: '', username: '', phone: '', role: 'TEACHER' as 'TEACHER' | 'ASSISTANT' })
async function load() { loading.value = true; try { rows.value = await getStaff(search.value) as Staff[] } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tải nhân sự' } finally { loading.value = false } }
async function create() { errorMessage.value = ''; successMessage.value = ''; try { const result = await adminCreateUser({ role: form.value.role, username: form.value.username, phone: form.value.phone || undefined, display_name: form.value.full_name, staff: { staff_code: form.value.staff_code || undefined, full_name: form.value.full_name } }); temporaryPassword.value = result.temporary_password; successMessage.value = 'Đã tạo tài khoản nhân sự. Mật khẩu tạm thời chỉ hiển thị một lần.'; showForm.value = false; form.value = { full_name: '', staff_code: '', username: '', phone: '', role: 'TEACHER' }; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể tạo nhân sự' } }
async function toggleStatus(row: Staff) { try { await setAccountStatus(row.user_id, row.status === 'ACTIVE' ? 'LOCKED' : 'ACTIVE'); successMessage.value = row.status === 'ACTIVE' ? 'Đã khóa tài khoản.' : 'Đã mở khóa tài khoản.'; await load() } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể đổi trạng thái tài khoản' } }
async function resetPassword(row: Staff) { try { const result = await adminResetPassword(row.user_id); temporaryPassword.value = result.temporary_password; successMessage.value = `Mật khẩu tạm của ${row.full_name} chỉ hiển thị một lần.` } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Không thể reset mật khẩu' } }
onMounted(load)
</script>

<template>
  <div class="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><div class="small text-secondary">Core</div><h1 class="h3 mb-0">Nhân sự</h1></div><button class="btn btn-primary" @click="showForm = !showForm">{{ showForm ? 'Đóng form' : 'Thêm nhân sự' }}</button></div>
  <div v-if="successMessage" class="alert alert-success">{{ successMessage }} <code>{{ temporaryPassword }}</code></div><div v-if="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
  <div v-if="showForm" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-5"><label class="form-label">Họ tên</label><input v-model="form.full_name" class="form-control" /></div><div class="col-md-3"><label class="form-label">Mã nhân sự</label><input v-model="form.staff_code" class="form-control" /></div><div class="col-md-4"><label class="form-label">Username</label><input v-model="form.username" class="form-control" placeholder="Tự sinh nếu bỏ trống" /></div><div class="col-md-4"><label class="form-label">Số điện thoại</label><input v-model="form.phone" class="form-control" /></div><div class="col-md-4"><label class="form-label">Vai trò</label><select v-model="form.role" class="form-select"><option value="TEACHER">Giáo viên</option><option value="ASSISTANT">Trợ giảng</option></select></div></div><button class="btn btn-success mt-3" :disabled="!form.full_name" @click="create">Tạo tài khoản</button></div></div>
  <div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex gap-2 mb-3"><input v-model="search" class="form-control" placeholder="Tìm theo tên hoặc mã" @keyup.enter="load" /><button class="btn btn-outline-primary" @click="load">Tìm</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Mã</th><th>Họ tên</th><th>Vai trò</th><th>SĐT</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.staff_code || '—' }}</td><td class="fw-semibold">{{ row.full_name }}</td><td>{{ row.staff_type === 'TEACHER' ? 'Giáo viên' : 'Trợ giảng' }}</td><td>{{ row.phone || '—' }}</td><td><span class="badge" :class="row.status === 'ACTIVE' ? 'text-bg-success' : 'text-bg-secondary'">{{ row.status }}</span></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-secondary" @click="toggleStatus(row)">{{ row.status === 'ACTIVE' ? 'Khóa' : 'Mở khóa' }}</button><button class="btn btn-sm btn-outline-warning" @click="resetPassword(row)">Reset mật khẩu</button></div></td></tr><tr v-if="!loading && !rows.length"><td colspan="6" class="text-center text-secondary py-4">Chưa có dữ liệu</td></tr></tbody></table></div></div></div>
</template>
