-- Generated from docs/data_seed/t9/*.xlsm by scripts/import_t9_attendance.py.
-- Source workbook formulas are not evaluated; cached OOXML values are imported.
-- This migration is fail-closed: any existing conflicting row aborts the transaction.
do $$
declare
  v_actor uuid;
  v_session record;
begin
  select p.user_id into v_actor
  from public.profiles p
  where p.role = 'ROOT_ADMIN' and p.status = 'ACTIVE'
  order by p.created_at, p.user_id
  limit 1;
  if v_actor is null then raise exception 'T9_IMPORT_NO_ACTIVE_ROOT_ADMIN'; end if;

  create temporary table t9_import_sessions (
    class_code text not null,
    session_date date not null,
    schedule_start time not null,
    schedule_end time not null,
    source_metadata jsonb not null,
    session_note text,
    complete_expected boolean not null,
    expected_revenue_rows integer not null,
    primary key (class_code, session_date, schedule_start, schedule_end)
  ) on commit drop;

  create temporary table t9_import_rows (
    class_code text not null,
    session_date date not null,
    schedule_start time not null,
    schedule_end time not null,
    student_code text not null,
    import_source_key text not null unique,
    status_raw text,
    attendance_status text,
    late_minutes integer,
    absence_reason text,
    homework_raw text,
    homework_score numeric(4,2),
    homework_note text,
    understanding_score smallint,
    attitude_score smallint,
    positive_feedback_count integer,
    positive_feedback_raw text,
    comment_raw text,
    assessment_snapshot jsonb not null,
    primary key (class_code, session_date, schedule_start, schedule_end, student_code)
  ) on commit drop;

  insert into pg_temp.t9_import_sessions values
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_class_label":"6.0","source_teacher_label":"Mạnh Cường","source_assistant_label":"Duy","block_selection_reason":"Đủ 19 học sinh; block D5 chỉ có 18 và các block lớp 9 không thuộc Toán 6.","timezone":"Asia/Ho_Chi_Minh","source_row_count":19,"assessment_snapshot_count":19,"attendance_count":19,"session_note_source":"6-9!A38"}'::jsonb, 'Nhìn chung cả lớp đều hiểu bài tuy nhiên mất trật tự rất nhiều', TRUE, 18),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_class_label":"7.0","source_teacher_label":"Phương Anh","source_assistant_label":"Quang Duy","block_selection_reason":"Block ngày 04/09 có đủ roster Toán 7.","timezone":"Asia/Ho_Chi_Minh","source_row_count":12,"assessment_snapshot_count":12,"attendance_count":12}'::jsonb, NULL, TRUE, 8),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_class_label":"9.0","source_teacher_label":"Phương Anh","source_assistant_label":"Quang Duy","block_selection_reason":"Sửa nhãn lớp 9 thành TOAN-7 theo roster và lịch; giữ Cao Nhật Minh trong snapshot vì thiếu trạng thái.","timezone":"Asia/Ho_Chi_Minh","source_row_count":12,"assessment_snapshot_count":12,"attendance_count":11}'::jsonb, NULL, FALSE, 10),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_class_label":"9.0","source_teacher_label":"Mạnh Cường","source_assistant_label":"Hà Anh","block_selection_reason":"Sửa nhãn lớp 9 thành TOAN-7 theo roster và lịch; giữ Cao Nhật Minh trong snapshot vì thiếu trạng thái.","timezone":"Asia/Ho_Chi_Minh","source_row_count":12,"assessment_snapshot_count":12,"attendance_count":11}'::jsonb, NULL, FALSE, 10),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_class_label":"9.0","source_teacher_label":"Mạnh Cường","source_assistant_label":"Hà Anh","block_selection_reason":"Chọn block ngày 13/09 đủ 12 học sinh; sửa nhãn lớp 9 thành TOAN-7 theo roster và lịch.","timezone":"Asia/Ho_Chi_Minh","source_row_count":12,"assessment_snapshot_count":12,"attendance_count":12}'::jsonb, NULL, TRUE, 11),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_class_label":"9.0","source_teacher_label":"Thầy dạy thay","source_assistant_label":"Hà Anh","block_selection_reason":"Block ngày 03/09 có dữ liệu; giữ nguyên nhãn giáo viên Thầy dạy thay trong metadata.","timezone":"Asia/Ho_Chi_Minh","source_row_count":9,"assessment_snapshot_count":9,"attendance_count":9,"source_lesson_label":"BUỔI 22: GIẢI PHƯƠNG TRÌNH"}'::jsonb, NULL, TRUE, 8),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_class_label":"9.0","source_teacher_label":"Nguyễn Mạnh Cường","source_assistant_label":"Phương Anh","block_selection_reason":"Block ngày 07/09 có dữ liệu; bỏ block dọc trùng.","timezone":"Asia/Ho_Chi_Minh","source_row_count":9,"assessment_snapshot_count":9,"attendance_count":9,"source_lesson_label":"BUỔI 23: CUNG VÀ DÂY CỦA 1 ĐƯỜNG TRÒN.","session_note_source":"Form đánh giá !I15"}'::jsonb, 'Lớp có tinh thần hoc tập ổn và chăm chú nghe bài. Tuy nhiên vẫn còn những nhược điểm sau: Bạn An, Đức đi học muộn và một số bạn quên mang compa. Trong giờ học một số em vẫn còn ồn ào gây ảnh hưởng tới lớp học bao gồm các em sau: An, Hùng, Đức. Mong thời gian tới lớp đi học đúng giờ, mang đầy đủ thiết bị học tập và giữ trật tự cũng như tôn trọng giáo viên để đạt được kết quả cao trong học tập. ', TRUE, 9),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_class_label":"9.0","source_teacher_label":"Nguyễn Mạnh Cường","source_assistant_label":"Tiền","block_selection_reason":"Block ngày 10/09 có dữ liệu; bỏ các bản sao và block ngày 14/09 trống.","timezone":"Asia/Ho_Chi_Minh","source_row_count":9,"assessment_snapshot_count":9,"attendance_count":9,"source_lesson_label":"BUỔI 24: CUNG VÀ DÂY CỦA 1 ĐƯỜNG TRÒN (TIẾP)"}'::jsonb, NULL, TRUE, 9);

  insert into pg_temp.t9_import_rows values
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-001', 't9:2026-09-03:TOAN-6:HS06-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 2, '2.0', 'Bạn Ngân ngồi học rất  ngoan chăm chú nghe giảng hiểu bản chất vấn đề và nắm được kiến thức cơ bản.Tuy nhiên trong lúc làm BT có khá ẩu dẫn đến sai sót. Bạn cần luyện tập các dạng bài thêm nhiều hơn và rèn kĩ năng cẩn thận hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":6,"student_code":"HS06-001","source_name":"Đào Thị Kim Ngân","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"2.0","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Bạn Ngân ngồi học rất  ngoan chăm chú nghe giảng hiểu bản chất vấn đề và nắm được kiến thức cơ bản.Tuy nhiên trong lúc làm BT có khá ẩu dẫn đến sai sót. Bạn cần luyện tập các dạng bài thêm nhiều hơn và rèn kĩ năng cẩn thận hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-002', 't9:2026-09-03:TOAN-6:HS06-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Phương Anh là bạn rất chăm chú nghe giảng và luôn tích cực phát biểu xây dựng bài. Bạn nắm chắc kiến thức cơ bản, tuy nhiên bạn còn rất ẩu dẫn đến những sai sót không đáng có trong quá trình làm bài. Bạn cần rèn luyện tính cẩn thận nhiều hơn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":7,"student_code":"HS06-002","source_name":"Đặng Phương Anh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Phương Anh là bạn rất chăm chú nghe giảng và luôn tích cực phát biểu xây dựng bài. Bạn nắm chắc kiến thức cơ bản, tuy nhiên bạn còn rất ẩu dẫn đến những sai sót không đáng có trong quá trình làm bài. Bạn cần rèn luyện tính cẩn thận nhiều hơn."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-003', 't9:2026-09-03:TOAN-6:HS06-003', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bạn Bảo đã có tiến bộ hơn về ý thức học tập, bạn đã tự giác làm bài và chăm chú nghe giảng hơn và nắm được các kiến thức cơ bản. Tuy nhiên đôi lúc bạn còn thiếu sự tập trung nên tốc độ làm bài còn chậm hơn các bạn. Bạn cần tập trung cao độ hơn trong các buổi học sau để đạt hiểu quả cao hơn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":8,"student_code":"HS06-003","source_name":"Nguyễn Gia Bảo","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Bảo đã có tiến bộ hơn về ý thức học tập, bạn đã tự giác làm bài và chăm chú nghe giảng hơn và nắm được các kiến thức cơ bản. Tuy nhiên đôi lúc bạn còn thiếu sự tập trung nên tốc độ làm bài còn chậm hơn các bạn. Bạn cần tập trung cao độ hơn trong các buổi học sau để đạt hiểu quả cao hơn."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-004', 't9:2026-09-03:TOAN-6:HS06-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bảo là một bạn nắm kiến thức rất chắc và luôn tích cực tham gia xây dựng bài, rất chăm chú nghe giảng.Tuy nhiên một số buổi gần đây tốc độ làm bài của bạn rất chậm và rất ẩu.Bạn cần lấy lại phong độ học tập và làm bài cẩn thận hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":9,"student_code":"HS06-004","source_name":"Nguyễn Đặng Gia Bảo","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bảo là một bạn nắm kiến thức rất chắc và luôn tích cực tham gia xây dựng bài, rất chăm chú nghe giảng.Tuy nhiên một số buổi gần đây tốc độ làm bài của bạn rất chậm và rất ẩu.Bạn cần lấy lại phong độ học tập và làm bài cẩn thận hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-005', 't9:2026-09-03:TOAN-6:HS06-005', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, '3.0', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":10,"student_code":"HS06-005","source_name":"Tuệ Lâm","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-006', 't9:2026-09-03:TOAN-6:HS06-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Linh rất chăm chú nghe giảng và tự giác học và làm bài.Tuy nhiên bạn khá nhút nhát ngại hỏi.Bạn cần mạnh dạn hỏi bài và phát biểu xây dựng bài nhiều hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":11,"student_code":"HS06-006","source_name":"Đặng Khánh Linh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Linh rất chăm chú nghe giảng và tự giác học và làm bài.Tuy nhiên bạn khá nhút nhát ngại hỏi.Bạn cần mạnh dạn hỏi bài và phát biểu xây dựng bài nhiều hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-007', 't9:2026-09-03:TOAN-6:HS06-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, NULL, NULL, 'Diệp là bạn rất chăm chú nghe giảng và rất sôi nổi phát biểu xây dựng bài. Bạn nắm chắc kiến thức cơ bản, tuy nhiên bạn còn rất ẩu dẫn đến những sai sót không đáng có trong quá trình làm bài. Bạn cần rèn luyện tính cẩn thận nhiều hơn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":12,"student_code":"HS06-007","source_name":"Nguyễn Ngọc Diệp","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Diệp là bạn rất chăm chú nghe giảng và rất sôi nổi phát biểu xây dựng bài. Bạn nắm chắc kiến thức cơ bản, tuy nhiên bạn còn rất ẩu dẫn đến những sai sót không đáng có trong quá trình làm bài. Bạn cần rèn luyện tính cẩn thận nhiều hơn."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-008', 't9:2026-09-03:TOAN-6:HS06-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 1, '1.0', 'Tú tuy vào học sau so với các bạn nhưng bạn nắm khá chắc kiến thức và mạnh dạn hỏi những bài chưa được học và chưa hiểu.Bạn cần phát huy tinh thần học tập này', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":13,"student_code":"HS06-008","source_name":"Nguyễn Ngọc Cẩm Tú","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Tú tuy vào học sau so với các bạn nhưng bạn nắm khá chắc kiến thức và mạnh dạn hỏi những bài chưa được học và chưa hiểu.Bạn cần phát huy tinh thần học tập này"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-009', 't9:2026-09-03:TOAN-6:HS06-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 3, '3.0', 'Bạn Hoàng đã có tiến bộ hơn về ý thức học tập, bạn đã tự giác làm bài và chăm chú nghe giảng hơn và nắm được các kiến thức cơ bản. Tuy nhiên đôi lúc bạn còn thiếu sự tập trung nên tốc độ làm bài còn chậm hơn các bạn. Bạn cần tập trung cao độ hơn trong các buổi học sau để đạt hiểu quả cao hơn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":14,"student_code":"HS06-009","source_name":"Đào Thế Hoàng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Hoàng đã có tiến bộ hơn về ý thức học tập, bạn đã tự giác làm bài và chăm chú nghe giảng hơn và nắm được các kiến thức cơ bản. Tuy nhiên đôi lúc bạn còn thiếu sự tập trung nên tốc độ làm bài còn chậm hơn các bạn. Bạn cần tập trung cao độ hơn trong các buổi học sau để đạt hiểu quả cao hơn."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-010', 't9:2026-09-03:TOAN-6:HS06-010', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, NULL, NULL, 'Bình An là một bạn khá thông minh, chăm chú nghe giảng. Tuy nhiên bạn còn rất ẩu trong quá trình làm bài khiến làm bài sai khá nhiều.Bạn cần rèn luyện tính cẩn thận để đạt kết quả cao hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":15,"student_code":"HS06-010","source_name":"Đào Nguyễn Bình An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Bình An là một bạn khá thông minh, chăm chú nghe giảng. Tuy nhiên bạn còn rất ẩu trong quá trình làm bài khiến làm bài sai khá nhiều.Bạn cần rèn luyện tính cẩn thận để đạt kết quả cao hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-011', 't9:2026-09-03:TOAN-6:HS06-011', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'My đã có tiến bộ hơn nắm đa số kiến thức cơ bản đã học.Bạn cần rèn luyện thêm các kiến thức để đạt kết quả cao hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":16,"student_code":"HS06-011","source_name":"Nguyễn Trà My","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"My đã có tiến bộ hơn nắm đa số kiến thức cơ bản đã học.Bạn cần rèn luyện thêm các kiến thức để đạt kết quả cao hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-012', 't9:2026-09-03:TOAN-6:HS06-012', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Dũng đã có tiến bộ hơn khá nhiều so với những buổi đầu vào học cùng các bạn.Tuy nhiên các kiến thức cơ bản của bạn còn chưa nắm vững nên đôi lúc làm bài còn khá ;úng túng.Bạn cần ôn lại các kiến thức đã học để đạt kiến quả tốt hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":17,"student_code":"HS06-012","source_name":"Bảo Dũng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Dũng đã có tiến bộ hơn khá nhiều so với những buổi đầu vào học cùng các bạn.Tuy nhiên các kiến thức cơ bản của bạn còn chưa nắm vững nên đôi lúc làm bài còn khá ;úng túng.Bạn cần ôn lại các kiến thức đã học để đạt kiến quả tốt hơn"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-013', 't9:2026-09-03:TOAN-6:HS06-013', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Minh là một trong những bạn khá thông minh trong lớp, đôi lúc bạn có những ý tưởng giải bài khá tốt, rất chăm chú nghe giảng và tự giác làm bài. Bạn cần tiếp tục duy trì phong độ học tập này', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":18,"student_code":"HS06-013","source_name":"Đào Quang Minh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Minh là một trong những bạn khá thông minh trong lớp, đôi lúc bạn có những ý tưởng giải bài khá tốt, rất chăm chú nghe giảng và tự giác làm bài. Bạn cần tiếp tục duy trì phong độ học tập này"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-014', 't9:2026-09-03:TOAN-6:HS06-014', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bạn Duy có ý thức học tập khá tốt,khá tập trung vào bài.Tuy nhiên bạn đôi lúc chưa tự giác làm những bài được giao và chưa tập trung vào buổi học.Bạn cần tập trung vào buổi học và tự giác học và làm bài hơn để đạt hiệu quả cao hơn trong buổi học', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":19,"student_code":"HS06-014","source_name":"Duy","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Duy có ý thức học tập khá tốt,khá tập trung vào bài.Tuy nhiên bạn đôi lúc chưa tự giác làm những bài được giao và chưa tập trung vào buổi học.Bạn cần tập trung vào buổi học và tự giác học và làm bài hơn để đạt hiệu quả cao hơn trong buổi học"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-015', 't9:2026-09-03:TOAN-6:HS06-015', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bạn Phúc rất chăm chú nghe giảng, tiếp thu bài tốt và tích cực tham gia xây dựng bài. Bạn có thái độ học tập nghiêm túc và chủ động, đây là điểm rất đáng khen. Hãy tiếp tục phát huy tinh thần này để ngày càng tiến bộ.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":20,"student_code":"HS06-015","source_name":"Phúc","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Phúc rất chăm chú nghe giảng, tiếp thu bài tốt và tích cực tham gia xây dựng bài. Bạn có thái độ học tập nghiêm túc và chủ động, đây là điểm rất đáng khen. Hãy tiếp tục phát huy tinh thần này để ngày càng tiến bộ."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-016', 't9:2026-09-03:TOAN-6:HS06-016', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bạn Thảo Linh có ý thức sửa sai tốt và đã rất cố gắng hoàn thiện lại những câu còn mắc lỗi. Tuy nhiên, đôi lúc bạn vẫn còn hơi ẩu khi làm bài nên dễ dẫn đến sai sót. Bạn cần đọc kỹ đề, kiểm tra lại từng bước trước khi kết luận để hạn chế những lỗi không đáng có.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":21,"student_code":"HS06-016","source_name":"Linh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Thảo Linh có ý thức sửa sai tốt và đã rất cố gắng hoàn thiện lại những câu còn mắc lỗi. Tuy nhiên, đôi lúc bạn vẫn còn hơi ẩu khi làm bài nên dễ dẫn đến sai sót. Bạn cần đọc kỹ đề, kiểm tra lại từng bước trước khi kết luận để hạn chế những lỗi không đáng có."}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-017', 't9:2026-09-03:TOAN-6:HS06-017', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Hân khá chăm chú nghe giảng và tự giác học tập.Bạn cần duy trì thái độ học tập này để nắm vững hơn các kiến thức mà bạn chưa được học', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":22,"student_code":"HS06-017","source_name":"Hân","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Hân khá chăm chú nghe giảng và tự giác học tập.Bạn cần duy trì thái độ học tập này để nắm vững hơn các kiến thức mà bạn chưa được học"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-018', 't9:2026-09-03:TOAN-6:HS06-018', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Kiều Anh khá chăm chú nghe giảng và tự giác học tập.Bạn cần duy trì thái độ học tập này để nắm vững hơn các kiến thức mà bạn chưa được học', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":23,"student_code":"HS06-018","source_name":"Kiều Anh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Kiều Anh khá chăm chú nghe giảng và tự giác học tập.Bạn cần duy trì thái độ học tập này để nắm vững hơn các kiến thức mà bạn chưa được học"}'::jsonb),
    ('TOAN-6', '2026-09-03', '17:30'::time, '19:30'::time, 'HS06-019', 't9:2026-09-03:TOAN-6:HS06-019', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, 'Bạn Khang mới theo lớp nhưng có tinh thần học tập tốt. Tuy nhiên,đôi lúc còn chưa tập trung vào làm bài. Bạn cần tập trung hơn vào buổi học, tránh nói chuyện để buổi học nâng cao hiệu quả hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_6.xlsm","source_sheet":"Form đánh giá","source_block":"J5","source_row":24,"student_code":"HS06-019","source_name":"Khang","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Bạn Khang mới theo lớp nhưng có tinh thần học tập tốt. Tuy nhiên,đôi lúc còn chưa tập trung vào làm bài. Bạn cần tập trung hơn vào buổi học, tránh nói chuyện để buổi học nâng cao hiệu quả hơn"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-001', 't9:2026-09-04:TOAN-7:HS07-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 4, '4', 'Hiểu bài, ý thức tốt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":6,"student_code":"HS07-001","source_name":"Lê Ngọc Ánh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"4","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Hiểu bài, ý thức tốt"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-002', 't9:2026-09-04:TOAN-7:HS07-002', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":7,"student_code":"HS07-002","source_name":"Nguyễn Thị Hồng Hạnh","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-003', 't9:2026-09-04:TOAN-7:HS07-003', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":8,"student_code":"HS07-003","source_name":"Nguyễn Văn Phúc","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-004', 't9:2026-09-04:TOAN-7:HS07-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 7, '7', 'Chú ý nghe giảng, tiếp thu bài nhanh', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":9,"student_code":"HS07-004","source_name":"Đào Thành Lê","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"7","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Chú ý nghe giảng, tiếp thu bài nhanh"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-005', 't9:2026-09-04:TOAN-7:HS07-005', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 2, '2', 'Tập trung làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":10,"student_code":"HS07-005","source_name":"Bùi Bảo Minh Anh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"2","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Tập trung làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-006', 't9:2026-09-04:TOAN-7:HS07-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7, '7', 'Có ý thức tốt, làm bài nhanh và chính xác', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":11,"student_code":"HS07-006","source_name":"Cao Nhật Minh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"7","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Có ý thức tốt, làm bài nhanh và chính xác"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-007', 't9:2026-09-04:TOAN-7:HS07-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 3, 4, 5, '5', 'Mất trật tự, chưa có ý thức tự giác làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":12,"student_code":"HS07-007","source_name":"Phạm Mạnh  Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"5","homework_raw":null,"understanding_raw":"3.0","attitude_raw":"4.0","comment_raw":"Mất trật tự, chưa có ý thức tự giác làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-008', 't9:2026-09-04:TOAN-7:HS07-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 7, '7', 'Có tính tự giác cao, hiểu bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":13,"student_code":"HS07-008","source_name":"Nghiêm Trung Hiếu","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"7","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Có tính tự giác cao, hiểu bài"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-009', 't9:2026-09-04:TOAN-7:HS07-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 6, '6', 'Làm bài nhanh và chính xác, có tinh thần tự học', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":14,"student_code":"HS07-009","source_name":"Trương Thủy Tiên","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"6","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Làm bài nhanh và chính xác, có tinh thần tự học"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-010', 't9:2026-09-04:TOAN-7:HS07-010', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":15,"student_code":"HS07-010","source_name":"Nguyễn Bảo An","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-011', 't9:2026-09-04:TOAN-7:HS07-011', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '2', 'Có ý thức tốt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":16,"student_code":"HS07-011","source_name":"Nguyễn Hải Đăng","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":"2","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Có ý thức tốt"}'::jsonb),
    ('TOAN-7', '2026-09-04', '17:30'::time, '19:30'::time, 'HS07-012', 't9:2026-09-04:TOAN-7:HS07-012', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"D5","source_row":17,"student_code":"HS07-012","source_name":"Đào Ngọc Lan","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-001', 't9:2026-09-06:TOAN-7:HS07-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, '11', 'Ý thức tốt, hiểu bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":6,"student_code":"HS07-001","source_name":"Lê Ngọc Ánh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"11","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, hiểu bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-002', 't9:2026-09-06:TOAN-7:HS07-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, '5', 'Ý thức tốt, chăm chỉ làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":7,"student_code":"HS07-002","source_name":"Nguyễn Thị Hồng Hạnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"5","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, chăm chỉ làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-003', 't9:2026-09-06:TOAN-7:HS07-003', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, '4', 'Ý thức tốt, chăm chỉ làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":8,"student_code":"HS07-003","source_name":"Nguyễn Văn Phúc","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"4","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, chăm chỉ làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-004', 't9:2026-09-06:TOAN-7:HS07-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, '5', 'Ý thức tốt, chăm chỉ làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":9,"student_code":"HS07-004","source_name":"Đào Thành Lê","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"5","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, chăm chỉ làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-005', 't9:2026-09-06:TOAN-7:HS07-005', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":10,"student_code":"HS07-005","source_name":"Bùi Bảo Minh Anh","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-006', 't9:2026-09-06:TOAN-7:HS07-006', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, '6', 'Ý thức tốt, chăm chỉ làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":11,"student_code":"HS07-006","source_name":"Cao Nhật Minh","status_raw":null,"attendance_status":null,"positive_feedback_raw":"6","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, chăm chỉ làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-007', 't9:2026-09-06:TOAN-7:HS07-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, '3', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":12,"student_code":"HS07-007","source_name":"Phạm Mạnh  Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-008', 't9:2026-09-06:TOAN-7:HS07-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, '8', 'Làm bài nhanh và chính xác, ý thức tốt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":13,"student_code":"HS07-008","source_name":"Nghiêm Trung Hiếu","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"8","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Làm bài nhanh và chính xác, ý thức tốt"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-009', 't9:2026-09-06:TOAN-7:HS07-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12, '12', 'Làm bài nhanh và chính xác,  có tinh thần tự giác', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":14,"student_code":"HS07-009","source_name":"Trương Thủy Tiên","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"12","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Làm bài nhanh và chính xác,  có tinh thần tự giác"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-010', 't9:2026-09-06:TOAN-7:HS07-010', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, '6', 'Làm bài nhanh và chính xác, ý thức tốt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":15,"student_code":"HS07-010","source_name":"Nguyễn Bảo An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"6","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Làm bài nhanh và chính xác, ý thức tốt"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-011', 't9:2026-09-06:TOAN-7:HS07-011', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, '4', 'Ý thức tốt, chăm chỉ làm bài', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":16,"student_code":"HS07-011","source_name":"Nguyễn Hải Đăng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"4","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Ý thức tốt, chăm chỉ làm bài"}'::jsonb),
    ('TOAN-7', '2026-09-06', '08:00'::time, '10:00'::time, 'HS07-012', 't9:2026-09-06:TOAN-7:HS07-012', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14, '14', 'Làm bài nhanh và chính xác,  có tinh thần tự giác', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"J5","source_row":17,"student_code":"HS07-012","source_name":"Đào Ngọc Lan","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"14","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":"Làm bài nhanh và chính xác,  có tinh thần tự giác"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-001', 't9:2026-09-11:TOAN-7:HS07-001', 'Có mặt', 'PRESENT', NULL, NULL, '10.0', 10.0, NULL, NULL, NULL, 3, '3', 'Tích cực giơ tay phát biểu, k ngại hỏi bài khi k biết làm, có ý thức tốt, ngoan', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":6,"student_code":"HS07-001","source_name":"Lê Ngọc Ánh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3","homework_raw":"10.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Tích cực giơ tay phát biểu, k ngại hỏi bài khi k biết làm, có ý thức tốt, ngoan"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-002', 't9:2026-09-11:TOAN-7:HS07-002', 'Có mặt', 'PRESENT', NULL, NULL, '6.0', 6.0, NULL, NULL, NULL, 1, '1', 'Chăm chú nghe giảng, tiếp thu kiến thức tốt, có ý thức tốt trong lớp', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":7,"student_code":"HS07-002","source_name":"Nguyễn Thị Hồng Hạnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1","homework_raw":"6.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Chăm chú nghe giảng, tiếp thu kiến thức tốt, có ý thức tốt trong lớp"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-003', 't9:2026-09-11:TOAN-7:HS07-003', 'Có mặt', 'PRESENT', NULL, NULL, '5.0', 5.0, NULL, NULL, NULL, 2, '2', 'Làm bài tập trên lớp tương đối nhanh, có tinh thần học hỏi, giơ tay phát biểu nhưng vẫn rất hay mất trật tự trong giờ', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":8,"student_code":"HS07-003","source_name":"Nguyễn Văn Phúc","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"2","homework_raw":"5.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Làm bài tập trên lớp tương đối nhanh, có tinh thần học hỏi, giơ tay phát biểu nhưng vẫn rất hay mất trật tự trong giờ"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-004', 't9:2026-09-11:TOAN-7:HS07-004', 'Có mặt', 'PRESENT', NULL, NULL, 'Không có BTVN', NULL, 'Không có BTVN', NULL, NULL, NULL, NULL, 'Ngoan, tiếp thu bài tốt, hoàn thành bài tập nhanh chóng và đầy đủ các nhiệm vụ được giao', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":9,"student_code":"HS07-004","source_name":"Đào Thành Lê","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":"Không có BTVN","understanding_raw":null,"attitude_raw":null,"comment_raw":"Ngoan, tiếp thu bài tốt, hoàn thành bài tập nhanh chóng và đầy đủ các nhiệm vụ được giao"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-005', 't9:2026-09-11:TOAN-7:HS07-005', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":10,"student_code":"HS07-005","source_name":"Bùi Bảo Minh Anh","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-006', 't9:2026-09-11:TOAN-7:HS07-006', NULL, NULL, NULL, NULL, '10.0', 10.0, NULL, NULL, NULL, 1, '1', 'Nắm chắc kiến thức đã học, làm bài tập nhanh và chính xác tuy nhiên cần ý thức trật tự trong giờ học hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":11,"student_code":"HS07-006","source_name":"Cao Nhật Minh","status_raw":null,"attendance_status":null,"positive_feedback_raw":"1","homework_raw":"10.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Nắm chắc kiến thức đã học, làm bài tập nhanh và chính xác tuy nhiên cần ý thức trật tự trong giờ học hơn"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-007', 't9:2026-09-11:TOAN-7:HS07-007', 'Có mặt', 'PRESENT', NULL, NULL, '8.0', 8.0, NULL, NULL, NULL, 3, '3', 'Tiếp thu kiến thức tốt nhưng chưa chủ động trong việc học, cần phải nhắc nhở nhiều và rất hay nói leo ồn ào mất trật tự', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":12,"student_code":"HS07-007","source_name":"Phạm Mạnh  Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3","homework_raw":"8.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Tiếp thu kiến thức tốt nhưng chưa chủ động trong việc học, cần phải nhắc nhở nhiều và rất hay nói leo ồn ào mất trật tự"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-008', 't9:2026-09-11:TOAN-7:HS07-008', 'Có mặt', 'PRESENT', NULL, NULL, 'Không có BTVN', NULL, 'Không có BTVN', NULL, NULL, 3, '3', 'Có tinh thần học hỏi cao, làm bài tập tốt và nhanh chóng, hăng hái giơ tay phát biểu nhưng vẫn hay nói leo', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":13,"student_code":"HS07-008","source_name":"Nghiêm Trung Hiếu","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3","homework_raw":"Không có BTVN","understanding_raw":null,"attitude_raw":null,"comment_raw":"Có tinh thần học hỏi cao, làm bài tập tốt và nhanh chóng, hăng hái giơ tay phát biểu nhưng vẫn hay nói leo"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-009', 't9:2026-09-11:TOAN-7:HS07-009', 'Có mặt', 'PRESENT', NULL, NULL, '4.5', 4.5, NULL, NULL, NULL, 2, '2', 'Rất ngoan, ý thức học tập tốt, hoàn thành bài tập về nhà và trên lớp đều đầy đủ, tiếp thu kiến thức nhanh. Cần tiếp tục phát huy', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":14,"student_code":"HS07-009","source_name":"Trương Thủy Tiên","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"2","homework_raw":"4.5","understanding_raw":null,"attitude_raw":null,"comment_raw":"Rất ngoan, ý thức học tập tốt, hoàn thành bài tập về nhà và trên lớp đều đầy đủ, tiếp thu kiến thức nhanh. Cần tiếp tục phát huy"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-010', 't9:2026-09-11:TOAN-7:HS07-010', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":15,"student_code":"HS07-010","source_name":"Nguyễn Bảo An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-011', 't9:2026-09-11:TOAN-7:HS07-011', 'Có mặt', 'PRESENT', NULL, NULL, '0.0', 0.0, NULL, NULL, NULL, NULL, NULL, 'Ngoan, có ý thức học tập và chấp hành tốt nội quy. Còn hơi rụt rè, chưa chủ động giơ tay phát biểu trong giờ. Cần mạnh dạn và tích cực tham gia xây dựng bài hơn', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":16,"student_code":"HS07-011","source_name":"Nguyễn Hải Đăng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":"0.0","understanding_raw":null,"attitude_raw":null,"comment_raw":"Ngoan, có ý thức học tập và chấp hành tốt nội quy. Còn hơi rụt rè, chưa chủ động giơ tay phát biểu trong giờ. Cần mạnh dạn và tích cực tham gia xây dựng bài hơn"}'::jsonb),
    ('TOAN-7', '2026-09-11', '17:30'::time, '19:30'::time, 'HS07-012', 't9:2026-09-11:TOAN-7:HS07-012', 'Có mặt', 'PRESENT', NULL, NULL, 'Không có BTVN', NULL, 'Không có BTVN', NULL, NULL, NULL, NULL, 'Nhanh nhẹn, hoạt bát và có tinh thần tham gia học tập. Tuy nhiên, đôi lúc còn nghịch và mất tập trung trong giờ. Cần chú ý giữ trật tự và tập trung hơn để đạt kết quả tốt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"P5","source_row":17,"student_code":"HS07-012","source_name":"Đào Ngọc Lan","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":"Không có BTVN","understanding_raw":null,"attitude_raw":null,"comment_raw":"Nhanh nhẹn, hoạt bát và có tinh thần tham gia học tập. Tuy nhiên, đôi lúc còn nghịch và mất tập trung trong giờ. Cần chú ý giữ trật tự và tập trung hơn để đạt kết quả tốt"}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-001', 't9:2026-09-13:TOAN-7:HS07-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '27+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":6,"student_code":"HS07-001","source_name":"Lê Ngọc Ánh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"27+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-002', 't9:2026-09-13:TOAN-7:HS07-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '16+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":7,"student_code":"HS07-002","source_name":"Nguyễn Thị Hồng Hạnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"16+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-003', 't9:2026-09-13:TOAN-7:HS07-003', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":8,"student_code":"HS07-003","source_name":"Nguyễn Văn Phúc","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"13+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-004', 't9:2026-09-13:TOAN-7:HS07-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":9,"student_code":"HS07-004","source_name":"Đào Thành Lê","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-005', 't9:2026-09-13:TOAN-7:HS07-005', 'Vắng', 'ABSENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":10,"student_code":"HS07-005","source_name":"Bùi Bảo Minh Anh","status_raw":"Vắng","attendance_status":"ABSENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-006', 't9:2026-09-13:TOAN-7:HS07-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '17+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":11,"student_code":"HS07-006","source_name":"Cao Nhật Minh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"17+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-007', 't9:2026-09-13:TOAN-7:HS07-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":12,"student_code":"HS07-007","source_name":"Phạm Mạnh  Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-008', 't9:2026-09-13:TOAN-7:HS07-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '21+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":13,"student_code":"HS07-008","source_name":"Nghiêm Trung Hiếu","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"21+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-009', 't9:2026-09-13:TOAN-7:HS07-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '27+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":14,"student_code":"HS07-009","source_name":"Trương Thủy Tiên","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"27+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-010', 't9:2026-09-13:TOAN-7:HS07-010', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '14+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":15,"student_code":"HS07-010","source_name":"Nguyễn Bảo An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"14+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-011', 't9:2026-09-13:TOAN-7:HS07-011', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":16,"student_code":"HS07-011","source_name":"Nguyễn Hải Đăng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"6+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-7', '2026-09-13', '08:00'::time, '10:00'::time, 'HS07-012', 't9:2026-09-13:TOAN-7:HS07-012', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '27+', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_7.xlsm","source_sheet":"Trang tính1","source_block":"V5","source_row":17,"student_code":"HS07-012","source_name":"Đào Ngọc Lan","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"27+","homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-001', 't9:2026-09-03:TOAN-9:HS09-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 3, 2, '2.0', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":6,"student_code":"HS09-001","source_name":"Trường An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"2.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"3.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-002', 't9:2026-09-03:TOAN-9:HS09-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":7,"student_code":"HS09-002","source_name":"Như Quỳnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-003', 't9:2026-09-03:TOAN-9:HS09-003', 'Vắng Có phép', 'EXCUSED', NULL, 'Có phép', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":8,"student_code":"HS09-003","source_name":"Huy Đức","status_raw":"Vắng Có phép","attendance_status":"EXCUSED","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-004', 't9:2026-09-03:TOAN-9:HS09-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":9,"student_code":"HS09-004","source_name":"Anh Trọng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-005', 't9:2026-09-03:TOAN-9:HS09-005', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 3, 3, '3.0', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":10,"student_code":"HS09-005","source_name":"Nguyễn Gia Bảo","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"3.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-006', 't9:2026-09-03:TOAN-9:HS09-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 3, 2, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":11,"student_code":"HS09-006","source_name":"Phạm Đức Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"3.0","attitude_raw":"2.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-007', 't9:2026-09-03:TOAN-9:HS09-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":12,"student_code":"HS09-007","source_name":"Quân","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-008', 't9:2026-09-03:TOAN-9:HS09-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 1, '1.0', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":13,"student_code":"HS09-008","source_name":"Phương Nhi","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-03', '17:30'::time, '19:30'::time, 'HS09-009', 't9:2026-09-03:TOAN-9:HS09-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 3, '3.0', NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"C5","source_row":14,"student_code":"HS09-009","source_name":"Lê Bảo Châm","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-001', 't9:2026-09-07:TOAN-9:HS09-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 3, 1, '1.0', 'An có năng lực học tập tốt, tiếp thu bài nhanh. Tuy nhiên, em cần đi học đúng giờ cũng như cải thiện thái độ, cách ứng xử với gv trong quá trình học. Cần điều chỉnh thái độ, tôn trọng gv và chủ động hợp tác để phát huy tốt năng lực của mình', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":6,"student_code":"HS09-001","source_name":"Trường An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"3.0","comment_raw":"An có năng lực học tập tốt, tiếp thu bài nhanh. Tuy nhiên, em cần đi học đúng giờ cũng như cải thiện thái độ, cách ứng xử với gv trong quá trình học. Cần điều chỉnh thái độ, tôn trọng gv và chủ động hợp tác để phát huy tốt năng lực của mình"}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-002', 't9:2026-09-07:TOAN-9:HS09-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 1, '1.0', 'Quỳnh có thái độ học tập tốt, ngoan và nghiêm túc trong quá trình học. Em có ý thức làm bài tập về nhà đầy đủ, hoàn thành bài khá tốt và có tinh thần hợp tác trong giờ học. Nhìn chung, em có ý thức học tập tốt và cần tiếp tục duy trì tinh thần này.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":7,"student_code":"HS09-002","source_name":"Như Quỳnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Quỳnh có thái độ học tập tốt, ngoan và nghiêm túc trong quá trình học. Em có ý thức làm bài tập về nhà đầy đủ, hoàn thành bài khá tốt và có tinh thần hợp tác trong giờ học. Nhìn chung, em có ý thức học tập tốt và cần tiếp tục duy trì tinh thần này."}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-003', 't9:2026-09-07:TOAN-9:HS09-003', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 3, 3, '3.0', 'Bạn Đức có tinh thần học bài và làm bài tốt, khả năng tiếp thu kiến thức cũng khá ổn. Tuy nhiên, bạn còn đi học muộn, gây mất trật tự và sử dụng lời nói chưa phù hợp trong giờ học. Bạn cần nghiêm túc hơn, giữ trật tự và chú ý đến cách giao tiếp để tạo môi trường học tập tốt cho bản thân và các bạn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":8,"student_code":"HS09-003","source_name":"Huy Đức","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"3.0","comment_raw":"Bạn Đức có tinh thần học bài và làm bài tốt, khả năng tiếp thu kiến thức cũng khá ổn. Tuy nhiên, bạn còn đi học muộn, gây mất trật tự và sử dụng lời nói chưa phù hợp trong giờ học. Bạn cần nghiêm túc hơn, giữ trật tự và chú ý đến cách giao tiếp để tạo môi trường học tập tốt cho bản thân và các bạn."}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-004', 't9:2026-09-07:TOAN-9:HS09-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 4, 1, '1.0', 'Trọng có khả năng tiếp thu bài tốt, chủ động và có tinh thần ham học hỏi. Em tích cực tiếp nhận kiến thức và có ý thức trong học tập. Tuy nhiên, em vẫn còn hơi mất trật tự trong giờ học, đôi lúc làm ảnh hưởng đến sự tập trung. Em cần chú ý giữ trật tự', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":9,"student_code":"HS09-004","source_name":"Anh Trọng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"4.0","comment_raw":"Trọng có khả năng tiếp thu bài tốt, chủ động và có tinh thần ham học hỏi. Em tích cực tiếp nhận kiến thức và có ý thức trong học tập. Tuy nhiên, em vẫn còn hơi mất trật tự trong giờ học, đôi lúc làm ảnh hưởng đến sự tập trung. Em cần chú ý giữ trật tự"}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-005', 't9:2026-09-07:TOAN-9:HS09-005', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 4, 4, '4.0', 'Bảo có khả năng học tập tốt, tiếp thu bài nhanh và nắm kiến thức khá chắc. Tuy nhiên, em còn có tình trạng nói chuyện riêng và đôi lúc nói leo trong giờ học. Em cần chú ý giữ trật tự, lắng nghe và chờ đến lượt phát biểu để tiết học đạt hiệu quả tốt hơn.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":10,"student_code":"HS09-005","source_name":"Nguyễn Gia Bảo","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"4.0","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"4.0","comment_raw":"Bảo có khả năng học tập tốt, tiếp thu bài nhanh và nắm kiến thức khá chắc. Tuy nhiên, em còn có tình trạng nói chuyện riêng và đôi lúc nói leo trong giờ học. Em cần chú ý giữ trật tự, lắng nghe và chờ đến lượt phát biểu để tiết học đạt hiệu quả tốt hơn."}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-006', 't9:2026-09-07:TOAN-9:HS09-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 3, 2, 3, '3.0', 'Hùng hiện còn gặp khá nhiều khó khăn trong việc tiếp thu và nắm kiến thức. Em chưa có ý thức làm bài tập đầy đủ, cả trên lớp và ở nhà, nên kết quả học tập chưa đạt yêu cầu. Trong giờ học, em còn khá ồn ào và chưa tập trung, ảnh hưởng đến hiệu quả', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":11,"student_code":"HS09-006","source_name":"Phạm Đức Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"3.0","attitude_raw":"2.0","comment_raw":"Hùng hiện còn gặp khá nhiều khó khăn trong việc tiếp thu và nắm kiến thức. Em chưa có ý thức làm bài tập đầy đủ, cả trên lớp và ở nhà, nên kết quả học tập chưa đạt yêu cầu. Trong giờ học, em còn khá ồn ào và chưa tập trung, ảnh hưởng đến hiệu quả"}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-007', 't9:2026-09-07:TOAN-9:HS09-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 3, '3.0', 'Quân rất ngoan, có thái độ học tập nghiêm túc và giữ trật tự tốt trong giờ học. Em chăm chỉ, có ý thức hoàn thành bài tập đầy đủ và đạt kết quả học tập tốt. Cần tiếp tục duy trì tinh thần học tập và ý thức này trong thời gian tới.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":12,"student_code":"HS09-007","source_name":"Quân","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"3.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Quân rất ngoan, có thái độ học tập nghiêm túc và giữ trật tự tốt trong giờ học. Em chăm chỉ, có ý thức hoàn thành bài tập đầy đủ và đạt kết quả học tập tốt. Cần tiếp tục duy trì tinh thần học tập và ý thức này trong thời gian tới."}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-008', 't9:2026-09-07:TOAN-9:HS09-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 4, 5, 1, '1.0', 'Nhi rất ngoan, có ý thức học tập và luôn cố gắng hoàn thành bài tập đầy đủ. Tuy nhiên, kết quả học tập của em hiện chưa được như mong muốn. Em còn khá rụt rè, chưa tự tin khi trao đổi và phát biểu trong giờ học. Em cần mạnh dạn hơn, tích cực đặt', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":13,"student_code":"HS09-008","source_name":"Phương Nhi","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"1.0","homework_raw":null,"understanding_raw":"4.0","attitude_raw":"5.0","comment_raw":"Nhi rất ngoan, có ý thức học tập và luôn cố gắng hoàn thành bài tập đầy đủ. Tuy nhiên, kết quả học tập của em hiện chưa được như mong muốn. Em còn khá rụt rè, chưa tự tin khi trao đổi và phát biểu trong giờ học. Em cần mạnh dạn hơn, tích cực đặt"}'::jsonb),
    ('TOAN-9', '2026-09-07', '17:30'::time, '19:30'::time, 'HS09-009', 't9:2026-09-07:TOAN-9:HS09-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, 5, 5, 4, '4.0', 'Bạn Châm có tinh thần học bài và làm bài tập về nhà rất tốt. Bạn thể hiện sự nghiêm túc và ý thức học tập tích cực. Bạn cần tiếp tục duy trì thói quen này, đồng thời chủ động hơn trong quá trình học để ngày càng tiến bộ.', '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"I5","source_row":14,"student_code":"HS09-009","source_name":"Lê Bảo Châm","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":"4.0","homework_raw":null,"understanding_raw":"5.0","attitude_raw":"5.0","comment_raw":"Bạn Châm có tinh thần học bài và làm bài tập về nhà rất tốt. Bạn thể hiện sự nghiêm túc và ý thức học tập tích cực. Bạn cần tiếp tục duy trì thói quen này, đồng thời chủ động hơn trong quá trình học để ngày càng tiến bộ."}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-001', 't9:2026-09-10:TOAN-9:HS09-001', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":6,"student_code":"HS09-001","source_name":"Trường An","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-002', 't9:2026-09-10:TOAN-9:HS09-002', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":7,"student_code":"HS09-002","source_name":"Như Quỳnh","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-003', 't9:2026-09-10:TOAN-9:HS09-003', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":8,"student_code":"HS09-003","source_name":"Huy Đức","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-004', 't9:2026-09-10:TOAN-9:HS09-004', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":9,"student_code":"HS09-004","source_name":"Anh Trọng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-005', 't9:2026-09-10:TOAN-9:HS09-005', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":10,"student_code":"HS09-005","source_name":"Nguyễn Gia Bảo","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-006', 't9:2026-09-10:TOAN-9:HS09-006', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":11,"student_code":"HS09-006","source_name":"Phạm Đức Hùng","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-007', 't9:2026-09-10:TOAN-9:HS09-007', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":12,"student_code":"HS09-007","source_name":"Quân","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-008', 't9:2026-09-10:TOAN-9:HS09-008', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":13,"student_code":"HS09-008","source_name":"Phương Nhi","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb),
    ('TOAN-9', '2026-09-10', '17:30'::time, '19:30'::time, 'HS09-009', 't9:2026-09-10:TOAN-9:HS09-009', 'Có mặt', 'PRESENT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"import_batch":"t9_2026_09","source_file":"Diem_danh_9.xlsm","source_sheet":"Form đánh giá ","source_block":"O5","source_row":14,"student_code":"HS09-009","source_name":"Lê Bảo Châm","status_raw":"Có mặt","attendance_status":"PRESENT","positive_feedback_raw":null,"homework_raw":null,"understanding_raw":null,"attitude_raw":null,"comment_raw":null}'::jsonb);

  create temporary table t9_resolved on commit drop as
  select r.*,
    cm.id as class_month_id, cms.id as schedule_id, s.id as session_id,
    ss.id as session_student_id, st.id as student_id,
    s.status as current_session_status, s.started_at, s.ended_at, s.revenue_snapshot,
    s.import_metadata as current_import_metadata, s.session_note as current_session_note
  from pg_temp.t9_import_rows r
  join public.classes c on c.code = r.class_code
  join public.class_months cm on cm.class_id = c.id and cm.year = 2026 and cm.month = 9
  join public.class_month_schedules cms on cms.class_month_id = cm.id
    and cms.status = 'ACTIVE'
    and cms.day_of_week = extract(isodow from r.session_date)::integer
    and cms.start_time = r.schedule_start and cms.end_time = r.schedule_end
  join public.sessions s on s.class_month_id = cm.id and s.schedule_id = cms.id
    and s.scheduled_start_at = ((r.session_date + r.schedule_start) at time zone 'Asia/Ho_Chi_Minh')
  join public.students st on st.student_code = r.student_code
  join public.session_students ss on ss.session_id = s.id and ss.student_id = st.id;

  if (select count(*) from pg_temp.t9_import_sessions) <> 8 then
    raise exception 'T9_IMPORT_SESSION_PAYLOAD_INVALID';
  end if;
  if (select count(*) from pg_temp.t9_import_rows) <> 94 then
    raise exception 'T9_IMPORT_ROW_PAYLOAD_INVALID';
  end if;
  if (select count(*) from pg_temp.t9_resolved) <> 94 then
    raise exception 'T9_IMPORT_LOOKUP_FAILED_EXPECTED_ROWS';
  end if;
  if exists (select 1 from pg_temp.t9_resolved where current_session_status = 'CANCELLED') then
    raise exception 'T9_IMPORT_SESSION_CANCELLED';
  end if;
  if exists (select 1 from pg_temp.t9_resolved where attendance_status is not null and attendance_status not in ('PRESENT','LATE','ABSENT','EXCUSED')) then
    raise exception 'T9_IMPORT_STATUS_MAPPING_INVALID';
  end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join public.student_attendances a on a.session_id = r.session_id and a.student_id = r.student_id
    where r.attendance_status is null or a.import_source_key is distinct from r.import_source_key
      or a.status::text is distinct from r.attendance_status
      or a.late_minutes is distinct from r.late_minutes
      or a.absence_reason is distinct from r.absence_reason
      or a.homework_score is distinct from r.homework_score
      or a.homework_note is distinct from r.homework_note
      or a.understanding_score is distinct from r.understanding_score
      or a.attitude_score is distinct from r.attitude_score
      or a.positive_feedback_count is distinct from r.positive_feedback_count
      or a.positive_feedback_raw is distinct from r.positive_feedback_raw
      or a.comment is distinct from r.comment_raw
  ) then raise exception 'T9_IMPORT_ATTENDANCE_CONFLICT'; end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join public.student_attendances a on a.import_source_key = r.import_source_key
    where a.session_id <> r.session_id or a.student_id <> r.student_id
  ) then raise exception 'T9_IMPORT_SOURCE_KEY_CONFLICT'; end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join public.session_students ss on ss.id = r.session_student_id
    where ss.assessment_snapshot <> r.assessment_snapshot
      and ss.assessment_snapshot <> '{}'::jsonb
  ) then raise exception 'T9_IMPORT_ASSESSMENT_SNAPSHOT_CONFLICT'; end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where r.current_import_metadata <> '{}'::jsonb
      and r.current_import_metadata <> i.source_metadata
  ) then raise exception 'T9_IMPORT_SESSION_METADATA_CONFLICT'; end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where r.current_session_note is not null and r.current_session_note is distinct from i.session_note
  ) then raise exception 'T9_IMPORT_SESSION_NOTE_CONFLICT'; end if;

  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where i.complete_expected and r.current_session_status not in ('SCHEDULED','COMPLETED')
  ) then raise exception 'T9_IMPORT_COMPLETION_STATUS_CONFLICT'; end if;
  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where not i.complete_expected and r.current_session_status <> 'SCHEDULED'
  ) then raise exception 'T9_IMPORT_PARTIAL_SESSION_STATUS_CONFLICT'; end if;
  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where i.complete_expected and r.current_session_status = 'COMPLETED'
      and r.current_import_metadata = '{}'::jsonb
  ) then raise exception 'T9_IMPORT_MANUAL_COMPLETED_SESSION_CONFLICT'; end if;

  update public.session_students ss
  set assessment_snapshot = r.assessment_snapshot
  from pg_temp.t9_resolved r
  where ss.id = r.session_student_id and ss.assessment_snapshot = '{}'::jsonb;

  insert into public.student_attendances (
    session_id, student_id, status, late_minutes, absence_reason, homework_score, homework_note,
    understanding_score, attitude_score, positive_feedback_count, positive_feedback_raw, comment, updated_by, import_source_key
  )
  select session_id, student_id, attendance_status::public.attendance_status, late_minutes, absence_reason, homework_score, homework_note,
    understanding_score, attitude_score, positive_feedback_count, positive_feedback_raw, comment_raw, v_actor, import_source_key
  from pg_temp.t9_resolved r
  where r.attendance_status is not null
  on conflict (session_id, student_id) do nothing;

  update public.sessions s
  set import_metadata = i.source_metadata,
      session_note = coalesce(s.session_note, i.session_note)
  from (
    select distinct r.session_id, i.source_metadata, i.session_note
    from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
  ) i
  where s.id = i.session_id and (s.import_metadata = '{}'::jsonb or s.session_note is null);

  update public.sessions s
  set status = 'COMPLETED', started_at = s.scheduled_start_at, started_by = v_actor,
      ended_at = s.scheduled_end_at, ended_by = v_actor, revenue_snapshot = i.expected_revenue
  from (
    select distinct r.session_id, i.complete_expected,
      (select coalesce(sum(ss2.session_unit_value), 0) from pg_temp.t9_resolved r2 join public.session_students ss2 on ss2.id = r2.session_student_id where r2.session_id = r.session_id and r2.attendance_status in ('PRESENT','LATE')) as expected_revenue
    from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
  ) i
  where s.id = i.session_id and i.complete_expected and s.status = 'SCHEDULED';

  if exists (
    select 1 from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
    where i.complete_expected and r.current_session_status = 'COMPLETED'
      and (r.started_at is distinct from (r.session_date + r.schedule_start) at time zone 'Asia/Ho_Chi_Minh'
        or r.ended_at is distinct from (r.session_date + r.schedule_end) at time zone 'Asia/Ho_Chi_Minh')
  ) then raise exception 'T9_IMPORT_COMPLETED_SESSION_TIMES_CONFLICT'; end if;

  for v_session in
    select distinct r.session_id, i.complete_expected, i.expected_revenue_rows
    from pg_temp.t9_resolved r
    join pg_temp.t9_import_sessions i using (class_code, session_date, schedule_start, schedule_end)
  loop
    if not exists (select 1 from public.audit_logs where action = 'SESSION_IMPORT_T9' and entity_type = 'sessions' and entity_id = v_session.session_id) then
      perform public.write_audit(
        v_actor, 'SESSION_IMPORT_T9', 'sessions', v_session.session_id,
        jsonb_build_object('status', 'SCHEDULED'),
        jsonb_build_object('status', case when v_session.complete_expected then 'COMPLETED' else 'SCHEDULED' end, 'attendance_rows', v_session.expected_revenue_rows),
        'Import attendance/assessment T9 09/2026 from docs/data_seed/t9'
      );
    end if;
  end loop;
end $$;

-- No timesheet, payroll, tuition, or accounting rows are created by this import.
